# Generated by Django 4.2.4 on 2023-08-31 16:32

import datetime
from datetime import datetime as dt
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_redditimage_id_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='redditimage',
            name='last_sent',
            field=models.DateTimeField(default=dt(2000, 1, 1, 6, 0, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='redditimage',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
