# Generated by Django 4.2.4 on 2023-09-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0006_delete_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="RunningCommand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_id", models.IntegerField()),
                ("command_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="redditimage",
            name="date_created",
        ),
        migrations.RemoveField(
            model_name="redditimage",
            name="last_sent",
        ),
    ]
