BAD_REDDIT_SITES = [
    "redgifs",
    "gfycat",
    "reddit.com/gallery",
    "i.imgur.com",
]

REDDIT_DATA_LOADS = {
    "all": 800,
    "year": 150,
    "month": 50,
    "week": 30,
}

# TODO předělat do db verze
SUBREDDITS = [
    "nsfw",
    "BonerMaterial",
    "iWantToFuckHer",
    "femalepov",
    "DirtyGaming",
    "Nudes",
    "Slut",
    "LegalTeens",
    "collegesluts",
    "18_19",
    "RealGirls",
    "Amateur",
    "UnderwearGW",
    "BDSMGW",
    "AsiansGoneWild",
    "gonewildcolor",
    "ecchi",
    "bdsm",
    "Bondage",
    "GWNerdy",
    "asshole",
    "AssholeBehindThong",
    "assholegonewild",
    "Boobies",
    "tits",
    "Nipples",
    "stockings",
    "legs",
    "datgap",
    "thighhighs",
    "thighdeology",
    "Blowjobs",
    "buttplug",
    "CelebrityButts",
    "cosplaybutts",
    "fitgirls",
    "celebnsfw",
    "cumsluts",
    "cumfetish",
    "amateurcumsluts",
    "thickloads",
    "before_after_cumsluts",
    "creampies",
    "FacialFun",
    "cumonclothes",
    "pussy",
    "rearpussy",
    "GodPussy",
    "Presenting",
    "PantiesToTheSide",
    "AsianHotties",
    "AsiansGoneWild",
    "realasians",
    "AsianNSFW",
    "NSFW_Japan",
    "redheads",
    "ginger",
    "palegirls",
    "SnowWhites",
    "TwinGirls",
    "facesitting",
    "lesbians",
    "StraightGirlsPlaying",
    "girlskissing",
    "holdthemoan",
    "grool",
    "OnOff",
    "seethru",
    "NSFWfashion",
    "ShinyPorn",
    "gothsluts",
    "NSFWCostumes",
    "Upskirt",
    "SchoolGirlSkirts",
    "leggingsgonewild",
    "lingerie",
]
